"pkg/core":
  - changed-files:
    - any-glob-to-any-file: packages/core/**/*
"pkg/types":
  - changed-files:
    - any-glob-to-any-file: packages/types/**/*
"pkg/walletconnect":
  - changed-files:
    - any-glob-to-any-file: packages/walletconnect/**/*
"kind/build":
  - changed-files:
    - any-glob-to-any-file: .editorconfig
    - any-glob-to-any-file: .eslintrc.json
    - any-glob-to-any-file: .yarnrc.yaml
    - any-glob-to-any-file: tsconfig.json
"kind/ci":
  - changed-files:
    - any-glob-to-any-file: .github/**/*.yml
    - any-glob-to-any-file: .mergify.yml
