name: Deploy docs
# This job builds and deploys documenation to github pages.
# It runs on every push to master with a change in the docs folder.
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - .github/workflows/deploy-docs.yaml

permissions:
  contents: read

jobs:
  Build-and-deploy:
    permissions:
      contents: write # for JamesIves/github-pages-deploy-action to push changes in repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          path: "."

      - name: Compute diff 📜
        uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            docs/**/*.*
          FILES: |
            package.json
            yarn.lock

      - name: Setup Protoc 👷
        if: env.GIT_DIFF
        uses: arduino/setup-protoc@v2
        with:
          version: "24.0"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 🔧
        if: env.GIT_DIFF
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock

      - name: Install 🔨
        if: env.GIT_DIFF
        run: yarn install --immutable

      - name: Build packages 🔧
        if: env.GIT_DIFF
        run: yarn build

      - name: Build docs 🔧
        if: env.GIT_DIFF
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: yarn build-docs

      - name: Prepare docs folder 🔧
        if: env.GIT_DIFF
        run: mv docs/build ~/output

      - name: Deploy 🚀
        if: env.GIT_DIFF
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: ~/output
          single-commit: true
          clean: true
          clean-excludes: |
            CNAME
