name: Release
# Release workflow builds the binaries for a release, and then publishes them to NPM.

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Protoc 👷
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node 👷
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Unshallow 🔨
        run: git fetch --prune --unshallow --tags --force

      - name: Install 🔨
        run: yarn install --immutable

      - name: Build 🔨
        run: yarn build

      - name: Create release 📜
        if: startsWith(github.ref, 'refs/tags/v')
        run: yarn publish-latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
