name: Tests

on:
  pull_request:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: yarn install
        run: yarn install

      - name: yarn install
        run: yarn build

      - name: Run core unit tests
        run: yarn workspace @desmoslabs/desmjs unit-tests

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: yarn install
        run: yarn install

      - name: yarn install
        run: yarn build

      - name: Download desmos bin
        run: |
          scripts/get_desmos_bin.sh 4.2.0
          scripts/spawn_test_chain.sh -b
          sleep 10
          yarn workspace @desmoslabs/desmjs integration-tests
