name: Tests

on:
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node 👷
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install protobuf compiler 🔨
        run: |
          sudo apt-get update
          sudo apt-get -y install protobuf-compiler

      - name: Install 🔨
        run: yarn install --immutable

      - name: Build 🔨
        run: yarn build

      - name: Run core unit tests
        run: yarn workspace @desmoslabs/desmjs unit-tests

      - name: Run core integration tests
        run: |
          scripts/get_desmos_bin.sh 4.2.0
          scripts/spawn_test_chain.sh -b
          sleep 10
          scripts/setup_chain.sh
          yarn workspace @desmoslabs/desmjs integration-tests
